# Sample of kubeadm.yaml for debug hyperkube
apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
useHyperKubeImage: true							# use hyperkube 
imageRepository: "taosy"                        # permit use default registry: "k8s.gcr.io/"
kubernetesVersion: "v1.15.113"					# version: have a strict format 
networking:
  podSubnet: 10.244.0.0/16						# for requirements of flannel
