apiVersion: v1
kind: ReplicationController
metadata:
  name: test3
  labels:
    run: test3
spec:
  replicas: 1
  selector:
    run: test3
  template:
    metadata:
      labels:
        run: test3
    spec:
      containers:
      - name: test3
        image: taosy/toolbox-k4.14:0.02
        command:
          - bash
        args:
          - -c
          - " ls -l /dev; sleep 5 "
        volumeMounts:
        - name: dev
          mountPath: /dev
      volumes:
        - name: dev
          hostPath:
            path: /dev

