apiVersion: v1
kind: ReplicationController
metadata:
  name: test2
  labels:
    run: test2
spec:
  replicas: 1
  selector:
    run: test2
  template:
    metadata:
      labels:
        run: test2
    spec:
      containers:
      - name: test2
        image: taosy/toolbox-k4.14:0.02
        command:
          - bash
        args:
          - -c
          - " ls -l /home/taosy/work/tmp; sleep 5 "
        volumeMounts:
        - name: tmp
          mountPath: /home/taosy/work/tmp
      volumes:
        - name: tmp
          hostPath:
            path: /home/taosy/work/tmp

