apiVersion: v1
kind: ReplicationController
metadata:
  name: test1
  labels:
    run: test1
spec:
  replicas: 1
  selector:
    run: test1
  template:
    metadata:
      labels:
        run: test1
    spec:
      containers:
      - name: test1
        image: taosy/toolbox-k4.14:0.02
        command:
          - bash
        args:
          - -c
          - "for i in {1..10};do echo test string; sleep 1; done; echo done "
        ports:
        - containerPort: 8080
          protocol: TCP
