apiVersion: v1
kind: ReplicationController
metadata:
  name: test1
  labels:
    run: test1
spec:
  replicas: 1
  selector:
    run: test1
  template:
    metadata:
      labels:
        run: test1
    spec:
      containers:
      - name: test1
        image: taosy/toolbox-k4.14:0.02
        command:
          - bash
        args:
          - -c
          - " ls -l /home/taosy/work/; sleep 5 "
        volumeMounts:
        - name: tmp
          mountPath: /home/taosy/work/tmp
          subPath: subdir
          readOnly: true
      volumes:
        - name: tmp
          emptyDir: {}

