From ubuntu:18.04
RUN apt upgrade
RUN apt update
RUN apt install --fix-missing -y libprotobuf-c1  build-essential autoconf gawk bison  gcc make python3 openssl python3-protobuf libprotobuf-c-dev protobuf-c-compiler
COPY graphene_install.tar.gz /
RUN tar xvf graphene_install.tar.gz -C /opt/
RUN /opt/graphene/fixme.sh
RUN rm -f /graphene_install.tar.gz


