#!/bin/bash
alias kbga="kubectl get all -o wide"
alias kbgp="kubectl get pods -o wide"
alias kbdp="kubectl describe pods"
alias kbgn="kubectl get nodes -o wide"
alias kbdn="kubectl describe nodes"
alias kbgrs="kubectl get rs -o wide"
alias kbdrs="kubectl describe rs"
alias kbgrc="kubectl get rc -o wide"
alias kbdrc="kubectl describe rc"
alias kbgdp="kubectl get deploy -o wide"
alias kbddp="kubectl describe deploy"
alias kbgsvc="kubectl get svc -o wide"
alias kbdsvc="kubectl describe svc"
